crab kill -d crab_full_run2_DY_v1/
crab kill -d crab_full_run2_DY_v2/
crab kill -d crab_full_run2_LNuAJJ_EWK_test94X/
crab kill -d crab_full_run2_ST_s/
crab kill -d crab_full_run2_ST_tW_antitop/
crab kill -d crab_full_run2_ST_tW_top/
crab kill -d crab_full_run2_ST_t_2/
crab kill -d crab_full_run2_ST_tbar_2/
crab kill -d crab_full_run2_TTGJets_v1/
crab kill -d crab_full_run2_WGToLNuG/
crab kill -d crab_full_run2_WJets_v1_2/
crab kill -d crab_full_run2_WJets_v2_2/
crab kill -d crab_full_run2_WW_v1_2/
crab kill -d crab_full_run2_WW_v2_2/
crab kill -d crab_full_run2_WZ_v1_2/
crab kill -d crab_full_run2_WZ_v2_2/
crab kill -d crab_full_run2_ZA/
crab kill -d crab_full_run2_ZZ_v1_2/
crab kill -d crab_full_run2_ZZ_v2_2/
crab kill -d crab_full_run2_smuB_v1/
crab kill -d crab_full_run2_smuB_v2/
crab kill -d crab_full_run2_smuC_v1/
crab kill -d crab_full_run2_smuD_v1/
crab kill -d crab_full_run2_smuE_v1/
crab kill -d crab_full_run2_smuF_v1/
crab kill -d crab_full_run2_smuG_v1/
crab kill -d crab_full_run2_smuH_v1/
